#!/usr/bin/env python3
"""Divergence check for the schema-generated config reference (#212).

Extends the #203 CI-style suite: the configuration key reference is authored
in exactly one place (the lince-config JSON Schemas) and generated everywhere
else; this test fails when a generated copy is stale or hand-edited.

Run with:
    python3 scripts/tests/test_config_reference.py
"""

import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import gen_config_reference  # noqa: E402


class TestConfigReferenceInSync(unittest.TestCase):
    def test_generated_files_match_schema(self):
        for path, content in gen_config_reference.generate_files().items():
            rel = path.relative_to(REPO_ROOT)
            self.assertTrue(path.is_file(), f"missing generated file {rel}")
            self.assertEqual(
                path.read_text(encoding="utf-8"), content,
                f"{rel} is stale — regenerate with: python3 scripts/gen_config_reference.py",
            )

    def test_generated_files_carry_banner(self):
        for path, content in gen_config_reference.generate_files().items():
            self.assertIn("GENERATED by scripts/gen_config_reference.py", content,
                          f"{path} lost its generated banner")

    def test_every_v1_key_has_a_description(self):
        """The generation source must stay complete: every key in the two
        user-facing v1 schemas carries a description."""
        mod = gen_config_reference.load_lince_config()
        for name in ("sandbox-config", "dashboard-config"):
            schema = mod.SCHEMAS[name]
            for section, sub in schema.get("properties", {}).items():
                props = sub.get("properties")
                if props is None and isinstance(sub.get("additionalProperties"), dict):
                    props = sub["additionalProperties"].get("properties")
                for key, key_schema in (props or {}).items():
                    self.assertIn(
                        "description", key_schema,
                        f"{name}: [{section}].{key} has no description — "
                        "the generated reference would render a hole",
                    )


if __name__ == "__main__":
    unittest.main(verbosity=2)
