#!/usr/bin/env python3
"""gen_config_reference.py — generate the configuration key reference (#212).

Single-sourcing: the embedded JSON Schemas in lince-config (#203) carry
per-key descriptions and defaults; this script renders them as Markdown into
every place that used to hand-maintain a copy:

    lince-dashboard/skills/lince-configure/references/sandbox-config.md
    lince-dashboard/skills/lince-configure/references/dashboard-config.md
    docs/documentation/configuration-keys.md       (all schemas, docs site)

Divergence check: scripts/tests/test_config_reference.py (CI-style — fails
when a generated file is stale or the schema changed without regeneration).

Usage:
    python3 scripts/gen_config_reference.py            # (re)write all outputs
    python3 scripts/gen_config_reference.py --check    # exit 1 on divergence
"""

from __future__ import annotations

import argparse
import importlib.machinery
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILL_REFS = REPO_ROOT / "lince-dashboard" / "skills" / "lince-configure" / "references"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/gen_config_reference.py from the lince-config\n"
    "     JSON Schemas (#203/#212) — do NOT hand-edit. Regenerate with:\n"
    "         python3 scripts/gen_config_reference.py\n"
    "     Guarded by scripts/tests/test_config_reference.py. -->\n"
)


def load_lince_config():
    path = REPO_ROOT / "lince-config" / "lince-config"
    spec = importlib.util.spec_from_loader(
        "lince_config_genref",
        importlib.machinery.SourceFileLoader("lince_config_genref", str(path)),
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _type_label(schema: dict) -> str:
    if "enum" in schema:
        return " \\| ".join(f"`\"{v}\"`" for v in schema["enum"])
    t = schema.get("type", "any")
    if t == "array":
        item_t = schema.get("items", {}).get("type", "any")
        return f"list[{item_t}]"
    if t == "object":
        return "table"
    return {"boolean": "bool", "integer": "int", "string": "str"}.get(t, t)


def _default_label(schema: dict) -> str:
    if "default" not in schema:
        return "—"
    d = schema["default"]
    if isinstance(d, bool):
        return f"`{str(d).lower()}`"
    if isinstance(d, str):
        return f'`"{d}"`'
    if isinstance(d, list):
        import json
        return f"`{json.dumps(d)}`"
    return f"`{d}`"


def _key_rows(props: dict, required: list, lines: list[str]) -> None:
    lines.append("| Key | Type | Default | Description |")
    lines.append("|-----|------|---------|-------------|")
    for key, sub in props.items():
        desc = sub.get("description", "—").replace("\n", " ")
        if key in required:
            desc = f"**required** — {desc}"
        lines.append(f"| `{key}` | {_type_label(sub)} | {_default_label(sub)} | {desc} |")
    lines.append("")


def render_schema(schema: dict, heading_level: int = 2) -> list[str]:
    """Render one schema document: per top-level table a section with a key
    table; nested object tables recurse one level (e.g. [agents.<name>])."""
    h = "#" * heading_level
    lines: list[str] = []
    scalar_props = {}
    for section, sub in schema.get("properties", {}).items():
        if sub.get("type") == "object" and ("properties" in sub or "additionalProperties" in sub):
            continue
        scalar_props[section] = sub
    if scalar_props:
        lines.append(f"{h} Top-level keys")
        lines.append("")
        _key_rows(scalar_props, schema.get("required", []), lines)

    for section, sub in schema.get("properties", {}).items():
        if section in scalar_props:
            continue
        if "properties" in sub:
            lines.append(f"{h} `[{section}]`")
            lines.append("")
            if sub.get("description"):
                lines.append(sub["description"])
                lines.append("")
            _key_rows(sub["properties"], sub.get("required", []), lines)
        elif isinstance(sub.get("additionalProperties"), dict):
            entry = sub["additionalProperties"]
            lines.append(f"{h} `[{section}.<name>]`")
            lines.append("")
            desc = sub.get("description") or entry.get("description")
            if desc:
                lines.append(desc)
                lines.append("")
            if "properties" in entry:
                _key_rows(entry["properties"], entry.get("required", []), lines)
    return lines


def gen_skill_reference(mod, name: str, title: str, intro: str) -> str:
    lines = [GENERATED_BANNER, f"# {title}", "", intro, ""]
    lines += render_schema(mod.SCHEMAS[name])
    return "\n".join(lines).rstrip() + "\n"


def gen_docs_page(mod) -> str:
    order = [
        ("sandbox-config", "Sandbox configuration (`~/.agent-sandbox/config.toml`)"),
        ("dashboard-config", "Dashboard configuration (`~/.config/lince-dashboard/config.toml`)"),
        ("lince", "LINCE v2 policy file (`~/.config/lince/lince.toml`)"),
        ("registry-agent", "Agent registry entries (`registry.d/<agent>.toml`)"),
        ("registry-providers", "Provider table (`registry.d/providers.toml`)"),
    ]
    lines = [
        GENERATED_BANNER,
        "# Configuration Keys",
        "",
        "Complete key-by-key reference for every LINCE configuration file, "
        "generated from the published JSON Schemas (`schemas/*.schema.json`). "
        "Validate any file with `lince-config validate`; point a TOML LSP "
        "(Taplo) at the schemas for editor autocomplete.",
        "",
    ]
    for name, title in order:
        lines.append(f"## {title}")
        lines.append("")
        schema = mod.SCHEMAS[name]
        if schema.get("description"):
            lines.append(schema["description"])
            lines.append("")
        lines += render_schema(schema, heading_level=3)
    return "\n".join(lines).rstrip() + "\n"


def generate_files() -> dict[Path, str]:
    mod = load_lince_config()
    return {
        SKILL_REFS / "sandbox-config.md": gen_skill_reference(
            mod, "sandbox-config", "Sandbox Configuration Reference",
            "Key reference for `~/.agent-sandbox/config.toml`. "
            "Edit via `lince-config set <key> <value> --target sandbox`; "
            "validate with `lince-config validate --target sandbox`.",
        ),
        SKILL_REFS / "dashboard-config.md": gen_skill_reference(
            mod, "dashboard-config", "Dashboard Configuration Reference",
            "Key reference for `~/.config/lince-dashboard/config.toml`. "
            "Edit via `lince-config set <key> <value> --target dashboard`; "
            "validate with `lince-config validate --target dashboard`.",
        ),
        SKILL_REFS / "lince-policy.md": gen_skill_reference(
            mod, "lince", "LINCE v2 Policy File Reference",
            "Key reference for `~/.config/lince/lince.toml` (and the project "
            "overlay `<project>/.lince/lince.toml`, same schema without "
            "`version`). Compose with `lince-config apply`; edit with "
            "`lince-config set <key> <value> --target lince`; validate with "
            "`lince-config validate --target lince`.",
        ),
        REPO_ROOT / "docs" / "documentation" / "configuration-keys.md": gen_docs_page(mod),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify outputs match generation; exit 1 on divergence")
    args = parser.parse_args()

    files = generate_files()
    if args.check:
        stale = [
            str(path.relative_to(REPO_ROOT))
            for path, content in files.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print(f"config reference out of sync: {', '.join(stale)}", file=sys.stderr)
            print("Regenerate with: python3 scripts/gen_config_reference.py", file=sys.stderr)
            return 1
        print("config reference is in sync.")
        return 0

    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
